import Config from "../types/config.type";

export function getDefaultConfig(): Config[] {
  return [
    {
      key: "general.appName",
      value: "Share",
      defaultValue: "Share",
      type: "string",
    },
    {
      key: "general.showHomePage",
      value: "true",
      defaultValue: "true",
      type: "boolean",
    },
    {
      key: "general.defaultLanguage",
      value: "en-US",
      defaultValue: "en-US",
      type: "string",
    },
    {
      key: "general.appUrl",
      value: "http://localhost:3000",
      defaultValue: "http://localhost:3000",
      type: "string",
    },
    {
      key: "share.allowRegistration",
      value: "false",
      defaultValue: "false",
      type: "boolean",
    },
    {
      key: "share.allowUnauthenticatedShares",
      value: "false",
      defaultValue: "false",
      type: "boolean",
    },
    {
      key: "share.maxExpiration",
      value: "0 days",
      defaultValue: "0 days",
      type: "timespan",
    },
    {
      key: "share.defaultExpiration",
      value: "7 days",
      defaultValue: "7 days",
      type: "timespan",
    },
    {
      key: "share.shareIdLength",
      value: "8",
      defaultValue: "8",
      type: "number",
    },
    {
      key: "share.maxSize",
      value: "1000000000",
      defaultValue: "1000000000",
      type: "filesize",
    },
    {
      key: "share.chunkSize",
      value: "10000000",
      defaultValue: "10000000",
      type: "filesize",
    },
    {
      key: "share.autoOpenShareModal",
      value: "false",
      defaultValue: "false",
      type: "boolean",
    },
    {
      key: "share.fileRetentionPeriod",
      value: "0 days",
      defaultValue: "0 days",
      type: "timespan",
    },
    {
      key: "email.enableShareEmailRecipients",
      value: "false",
      defaultValue: "false",
      type: "boolean",
    },
    {
      key: "oauth.disablePassword",
      value: "false",
      defaultValue: "false",
      type: "boolean",
    },
    {
      key: "smtp.enabled",
      value: "false",
      defaultValue: "false",
      type: "boolean",
    },
    {
      key: "webdav.enabled",
      value: "true",
      defaultValue: "true",
      type: "boolean",
    },
    {
      key: "webdav.allowWrite",
      value: "true",
      defaultValue: "true",
      type: "boolean",
    },
    {
      key: "images.uploadEnabled",
      value: "true",
      defaultValue: "true",
      type: "boolean",
    },
    {
      key: "images.apiUploadEnabled",
      value: "true",
      defaultValue: "true",
      type: "boolean",
    },
    {
      key: "images.allowPublic",
      value: "true",
      defaultValue: "true",
      type: "boolean",
    },
    {
      key: "images.defaultPublic",
      value: "true",
      defaultValue: "true",
      type: "boolean",
    },
    {
      key: "images.maxSize",
      value: "26214400",
      defaultValue: "26214400",
      type: "filesize",
    },
    {
      key: "images.maxPixels",
      value: "40000000",
      defaultValue: "40000000",
      type: "number",
    },
    {
      key: "images.thumbnailSize",
      value: "480",
      defaultValue: "480",
      type: "number",
    },
    {
      key: "images.allowProcessing",
      value: "true",
      defaultValue: "true",
      type: "boolean",
    },
    {
      key: "images.userQuota",
      value: "0",
      defaultValue: "0",
      type: "filesize",
    },
    {
      key: "images.uploadsPerMinute",
      value: "30",
      defaultValue: "30",
      type: "number",
    },
    {
      key: "images.recycleRetentionDays",
      value: "30",
      defaultValue: "30",
      type: "number",
    },
    {
      key: "images.publicBaseUrl",
      value: "",
      defaultValue: "",
      type: "string",
    },
    {
      key: "images.cacheMaxAge",
      value: "86400",
      defaultValue: "86400",
      type: "number",
    },
    {
      key: "legal.enabled",
      value: "false",
      defaultValue: "false",
      type: "boolean",
    },
    { key: "legal.imprintText", value: "", defaultValue: "", type: "text" },
    { key: "legal.imprintUrl", value: "", defaultValue: "", type: "string" },
    {
      key: "legal.privacyPolicyText",
      value: "",
      defaultValue: "",
      type: "text",
    },
    {
      key: "legal.privacyPolicyUrl",
      value: "",
      defaultValue: "",
      type: "string",
    },
  ];
}
